//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Net.Sockets;
using System.Windows.Forms;
using NSUdp_shared;

namespace NSUdp_client {
    
    public partial class udp_clientForm {
        public udp_clientForm() {
            InitializeComponent();
        }
        void exitClick(object sender, EventArgs ea) {
            CancelEventArgs cea = new CancelEventArgs();

            Application.Exit(cea);
            if (cea.Cancel) {
                return;
            }
            Application.Exit();
        }
        UdpClient _client;

        void formLoad(object sender, EventArgs ea) {
            _client = SharedUDPDefinition.createUDPListener();
            _client.BeginReceive()
            
        }
        [STAThread()]
        public static void Main(string[] args) {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new udp_clientForm());
        }
    }
}
